name: Ruby Syntax
on: 
  push:
    branches:
      - master
      - staging
      - main
    paths:
      - "**/*.lic"
      - "**/*.rb"
      - "lich.rbw"
  pull_request:
    paths:
      - "**/*.lic"
      - "**/*.rb"
      - "lich.rbw"

jobs:
  check_syntax:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    name: Run tests on Ruby
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad # v47.0.5
        with:
          files: |
            **/*.lic
            **/*.rb
            lich.rbw
            
      - uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          bundler-cache: true
          
      - name: Run Ruby syntax check on changed scripts
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ruby -c $file
          done
